# Site settings
title: Mindbox Studios
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://voice.mindboxstudios.com"
twitter_username: mindboxstudios
github_username:  mindboxstudios

# Build settings
markdown: kramdown
sass:
    style: compressed
